instruction: |
  Prove or disprove the following statement, clearly indicating whether you believe it to be false or true:
strict_parsing: false
n_problems: 32
date: "2026-03-07"
final_answer: false
dataset_path: data/arxiv_false/february
judge_configs:
  - judges/arxiv_judge
