instruction: |
  Try to generate a proof for the following statement:
strict_parsing: false
n_problems: 31
date: "2026-03-07"
final_answer: false
dataset_path: data/arxiv_false/february
judge_configs:
  - judges/arxiv_judge
